### PR TITLE
bug(node/p2p): fix bootstrapping for enode addresses

### LINKED ISSUE #1413: fix(node/p2p): Bootstrapping
### Description

Currently, `kona-p2p` is unable to bootstrap using Enode (aka Multiaddr) node identifiers. Since we had bootnode ENRs for op mainnet, that was fine - only those ENRs were [used by the discovery service during bootstrapping](https://github.com/op-rs/kona/blob/main/crates/node/p2p/src/discv5/driver.rs#L96-L103). Enodes are ignored.

This ticket is to find a way to bootstrap with Enodes. For testnet, `kona-p2p` only has a [set of enode identifiers](https://github.com/op-rs/kona/blob/main/crates/node/p2p/src/peers/nodes.rs#L106-L119). Basically what happens when we run the kona-p2p networking stack for op-sepolia or some other testnet chain in the superchain is it is unable to add any peers in the discovery table - leaving the network stuck.

### PR DESCRIPTION
**Pull request by theochap**
## Description
This PR provides a fix for the bootstrapping of nodes given an enode address. 
In particular:
- it fixes the conversion from "local" `PeerId` to "p2plib" `PeerId`. These two types represent the same underlying concept (secp256k1 public key) but using different encodings (the local `PeerId` is the uncompressed representation of the public key, while the "p2plib" `PeerId` is a more complex representation, involving protobuf encoding and bitcoin encoding, defined here: https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md).
- It slightly changes the logic of the `bootstrap` method to ensure that both enode and enr encoded bootstrap nodes are added.
- It adds util methods for the conversion from local representation to "p2plib" representation of `PeerId`. 
- It adds unit testing to highlight the difference of format and ensure the conversion works.

As a follow-up, we should probably try and rename the "local" `PeerId`, or add type-safety/newtypes to ensure that we limit the likelihood of doing wrongful conversions in the future.

## Associated issue
Merging this PR will close #1413

### CODE REVIEW

File: crates/node/p2p/src/discv5/driver.rs [hunk 1]
```diff
@@ -125,25 +155,29 @@ impl Discv5Driver {
                 Err(e) => debug!("Failed to add ENR to discv5 table: {:?}", e),
             }
         }
-        info!("Added {} ENRs to discv5 | {} in bootstore", count, self.store.len());
 
         // Merge the bootnodes into the bootstore.
         self.store.merge(boot_enrs);
+        info!("Added {} ENRs to discv5 | {} in bootstore", count, self.store.len());
```
Comment (emhane) [inline crates/node/p2p/src/discv5/driver.rs:161]: can be downgraded to debug log level. and pls add so we can filter when debugging. we also tend to use the k=v format for values. see lighthouse or reth for reference.
```suggestion
        debug!(target: "p2p::discv5",
            new=%count,
            total=%self.store.len(),
            "Added new ENRs to discv5 bootstore"
        );
```
then we debug like,
`$ RUST_LOG=p2p::discv5=trace <kona-cmd>`

File: crates/node/p2p/src/discv5/driver.rs [hunk 2]
```diff
@@ -89,6 +90,35 @@ impl Discv5Driver {
         }
     }
 
+    /// Adds a bootnode to the discv5 service given an enode address.
+    async fn add_enode(&mut self, enode: Multiaddr) -> Option<Enr> {
+        let enr = match self.disc.request_enr(enode.clone()).await {
+            Ok(enr) => enr,
+            Err(err) => {
+                println!("Failed to add enr: {:?}", err);
```
[the remark this answers is not in the document]
Comment (emhane) [reply crates/node/p2p/src/discv5/driver.rs:98]: can keep the print statement for now but should be removed, ref https://github.com/op-rs/kona/issues/1437

File: crates/node/p2p/src/discv5/driver.rs [hunk 3]
```diff
@@ -89,6 +90,35 @@ impl Discv5Driver {
...
+                    %err,
+                    "failed to add boot node"
+                );
+
+                return None;
+            }
+        };
+
+        if let Err(err) = self.disc.add_enr(enr.clone()) {
+            error!(
```
Comment (emhane) [inline crates/node/p2p/src/discv5/driver.rs:109]: can be downgraded to `warn`. `error` is reserved for events which will make the node unable to progress. like for example zero boot nodes successfully added from boot node list.

File: crates/node/p2p/src/discv5/driver.rs [hunk 4]
```diff
@@ -125,25 +155,29 @@ impl Discv5Driver {
...
+                    boot_enodes_enrs.push(enr);
                 }
-                _ => { /* ignore: bootnode enrs already added */ }
+                BootNode::Enr(_) => { /* ignore: bootnode enrs already added */ }
             }
         }
+
+        // Merge the bootnodes into the bootstore.
+        self.store.merge(boot_enodes_enrs);
+        info!("Added {} ENRs to discv5 | {} in bootstore", count, self.store.len());
```
Comment (emhane) [inline crates/node/p2p/src/discv5/driver.rs]: can also be downgraded to debug, see above comment

File: crates/node/p2p/src/discv5/driver.rs [hunk 5]
```diff
@@ -276,4 +317,47 @@ mod tests {
         // The service starts.
         // TODO: verify with a heartbeat.
     }
+
+    #[tokio::test]
+    async fn test_discv5_driver_bootstrap_testnet() {
+        let socket = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)), 9099);
+        let mut discovery = Discv5Driver::builder()
+            .with_address(socket)
+            .with_chain_id(11155420)
```
Comment (emhane) [inline crates/node/p2p/src/discv5/driver.rs:333]: pls replace magic number with constant

File: crates/node/p2p/src/discv5/driver.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (theochap) [reply crates/node/p2p/src/discv5/driver.rs:98]: Good catch, definitely going to remove that

File: crates/node/p2p/src/discv5/driver.rs [hunk 6]
```diff
@@ -276,4 +317,47 @@ mod tests {
...
+            .expect("Failed to build discovery service");
+
+        discovery.init().await;
+
+        discovery.bootstrap().await;
+
+        // Verify bootstore has entries.
+        assert!(!discovery.store.is_empty(), "No nodes were added to the bootstore");
+        // Verify discv5 has entries in its enr table.
+        assert!(!discovery.disc.table_entries_enr().is_empty());
```
Comment (emhane) [inline crates/node/p2p/src/discv5/driver.rs:344]: this test runs on WAN it appears as opposed to the test being rigged on localhost spinning up boot nodes manually, this means this test is likely to be flaky and some point in future and fail CI. can we therefore limit this test to run on a nightly cronjob instead of on each pr?

**Review by emhane — CHANGES_REQUESTED** [review]

File: crates/node/p2p/src/discv5/driver.rs (hunk 5 above)
Comment (refcell) [reply crates/node/p2p/src/discv5/driver.rs:333]: Not a huge deal since it's in a test, but `kona-genesis` [exports the `OP_SEPOLIA_CHAIN_ID` constant](https://github.com/op-rs/kona/blob/main/crates/protocol/genesis/src/chain/mod.rs#L7).

File: crates/node/p2p/src/peers/utils.rs [hunk 7]
```diff
@@ -17,3 +19,76 @@ pub fn enr_to_multiaddr(enr: &Enr) -> Option<Multiaddr> {
...
+    secp256k1::PublicKey::from_slice(&s)
+}
+
+/// Converts an uncoded [`PeerId`] to a [`libp2p::PeerId`].
+pub fn local_id_to_p2p_id(peer_id: PeerId) -> Result<libp2p::PeerId, secp256k1::Error> {
+    // The libp2p library works with compressed public keys.
+    let encoded_pk_bytes = id2pk(peer_id)?.serialize();
+    let pk: discv5::libp2p_identity::PublicKey =
+        discv5::libp2p_identity::secp256k1::PublicKey::try_from_bytes(&encoded_pk_bytes)
+            .expect("secp256k1 serialization should be valid")
```
Comment (emhane) [inline crates/node/p2p/src/peers/utils.rs:49]: this is a place where it is tolerable to panic

File: crates/node/p2p/src/peers/utils.rs [hunk 8]
```diff
@@ -17,3 +19,76 @@ pub fn enr_to_multiaddr(enr: &Enr) -> Option<Multiaddr> {
...
+            .into();
+
+    Ok(pk.to_peer_id())
+}
```
Comment (emhane) [inline crates/node/p2p/src/peers/utils.rs:53]: make sure these functions are full test covered, i.e. all the error branches, seems like code cov is happy with them already :)

File: crates/node/p2p/src/peers/utils.rs [hunk 9]
```diff
@@ -17,3 +19,76 @@ pub fn enr_to_multiaddr(enr: &Enr) -> Option<Multiaddr> {
...
+
+        let p2p_public_key: discv5::libp2p_identity::PublicKey =
+            p2p_keypair.public().clone().into();
+
+        assert_eq!(peer_id, p2p_public_key.to_peer_id());
+    }
+
+    #[test]
+    fn test_hardcoded_peer_id() {
+        let pub_key_str = "548f715f3fc388a7c917ba644a2f16270f1ede48a5d88a4d14ea287cc916068363f3092e39936f1a3e7885198bef0e5af951f1d7b1041ce8ba4010917777e71f";
```
Comment (emhane) [inline crates/node/p2p/src/peers/utils.rs:78]: can be a const

File: crates/node/p2p/src/peers/utils.rs [hunk 10]
```diff
@@ -17,3 +19,76 @@ pub fn enr_to_multiaddr(enr: &Enr) -> Option<Multiaddr> {
...
+    use crate::{PeerId, peers::utils::id2pk};
+
+    use super::*;
+
+    #[test]
+    fn test_convert_local_peer_id_to_multi_peer_id() {
+        let p2p_keypair = discv5::libp2p_identity::secp256k1::Keypair::generate();
+        let uncompressed = p2p_keypair.public().to_bytes_uncompressed();
+        let local_peer_id = PeerId::from_slice(&uncompressed[1..]);
+        let peer_id = local_id_to_p2p_id(local_peer_id).unwrap();
```
Comment (emhane) [inline crates/node/p2p/src/peers/utils.rs:68]: agreed that the word local to p2p is unhelpful here, could you pls leave a smol code comment what local vs p2p refers to here

File: crates/node/p2p/src/discv5/driver.rs (hunk 5 above)
Comment (theochap) [reply crates/node/p2p/src/discv5/driver.rs]: Done!

File: crates/node/p2p/src/discv5/driver.rs (hunk 4 above)
Comment (theochap) [reply crates/node/p2p/src/discv5/driver.rs]: Done

File: crates/node/p2p/src/discv5/driver.rs (hunk 3 above)
Comment (theochap) [reply crates/node/p2p/src/discv5/driver.rs]: Done

**Review by emhane — CHANGES_REQUESTED** [review]
the pr has a really nice description, can we get some of that text better into docs?

File: crates/node/p2p/src/peers/utils.rs (hunk 9 above)
Comment (theochap) [reply crates/node/p2p/src/peers/utils.rs]: Done

File: crates/node/p2p/src/peers/utils.rs (hunk 7 above)
Comment (theochap) [reply crates/node/p2p/src/peers/utils.rs]: Changed that to graceful error

**Comment by theochap** [comment]
> the pr has a really nice description, can we get some of that text better into docs?

I put some part of the description inside the method that converts the local peer id to the libp2p peer id (`local_id_to_p2p_id`)

File: crates/node/p2p/src/peers/utils.rs (hunk 10 above)
Comment (theochap) [reply crates/node/p2p/src/peers/utils.rs:83]: Added a doc comment

File: crates/node/p2p/src/discv5/driver.rs (hunk 6 above)
Comment (emhane) [reply crates/node/p2p/src/discv5/driver.rs:345]: sure, this test isn't controlled fully in this scope because it depends on the liveness of boot nodes in the testnet. the testnet is not controlled by this test. if those nodes go offline, then ci will fail and we can't merge prs.

Comment (emhane) [reply crates/node/p2p/src/discv5/driver.rs:345]: it doesn't make sense to make ci passing dependent on if those boot nodes are online or not.

does that make sense?

File: crates/node/p2p/src/peers/any.rs [hunk 11]
```diff
@@ -27,17 +37,21 @@ impl AnyNode {
...
+        let pub_key: discv5::libp2p_identity::PublicKey =
+            discv5::libp2p_identity::secp256k1::PublicKey::try_from_bytes(
+                &id2pk(self.peer_id()).map_err(DialOptsError::InvalidPeerId)?.serialize(),
+            )?
+            .into();
+
+        let libp2p_id = libp2p::PeerId::from_public_key(&pub_key);
         Ok(libp2p_id.into())
     }
 }
```
Comment (emhane) [inline crates/node/p2p/src/peers/any.rs:50]: here we want full test coverage too or are we 100% it is infallible because it's converting the local peer id which will always be the correct number of bytes, so we can use expect here too?

**Review by emhane — CHANGES_REQUESTED** [review]

File: crates/node/p2p/src/discv5/driver.rs (hunk 6 above)
Comment (theochap) [reply crates/node/p2p/src/discv5/driver.rs:345]: Just pushed a change https://github.com/op-rs/kona/pull/1435/commits/e27c1490338377020aa1c1ef1b9979fb516a9569#diff-e3c2d30d9bcd63009fc8fd07a05b5a190843f0c2b78f8c58f5d63493288c64ecR345

File: crates/node/p2p/src/peers/any.rs (hunk 11 above)
Comment (theochap) [reply crates/node/p2p/src/peers/any.rs:50]: Exactly: in theory we should never raise the outer err because we know that `PeerId::serialize` will always yield the right byte sequence

Comment (emhane) [reply crates/node/p2p/src/peers/any.rs:50]: apparently you can use
```rust
// coverage:ignore-start
fn not_covered() {
    println!("This is ignored for coverage");
}
// coverage:ignore-end
```
for codecov to ignore these lines, then you don't need to replace the error propagation for the panics here

**Review by emhane — APPROVED** [review]

File: crates/node/p2p/src/peers/utils.rs [hunk 12]
```diff
@@ -17,3 +19,93 @@ pub fn enr_to_multiaddr(enr: &Enr) -> Option<Multiaddr> {
...
+/// bytes with the `SECP256K1_TAG_PUBKEY_UNCOMPRESSED` tag.
+#[inline]
+pub fn id2pk(id: PeerId) -> Result<secp256k1::PublicKey, secp256k1::Error> {
+    // NOTE: B512 is used as a PeerId because 512 bits is enough to represent an uncompressed
+    // public key.
+    let mut s = [0u8; secp256k1::constants::UNCOMPRESSED_PUBLIC_KEY_SIZE];
+    s[0] = SECP256K1_TAG_PUBKEY_UNCOMPRESSED;
+    s[1..].copy_from_slice(id.as_slice());
+    secp256k1::PublicKey::from_slice(&s)
+}
```
Comment (emhane) [inline crates/node/p2p/src/peers/utils.rs:41]: hm, this is identical to the reth code could be good to switch it up so as to not violate copyright or add their licenses to this file. up to you, each is on there own wrt copyrights as by contract I believe.

Comment (theochap) [reply crates/node/p2p/src/peers/utils.rs:41]: I thought this was ok because we have the following disclaimer here: https://github.com/op-rs/kona/blob/e7cadd2600183b52ffb2eed75102ddf981c91fa4/crates/node/p2p/src/peers/mod.rs#L1-L4. Isn't that enough?

Comment (theochap) [reply crates/node/p2p/src/peers/utils.rs]: Changed the code to not match reth's
