### PR TITLE
fix(supervisor): activation block reorg cases

### LINKED ISSUE #2668: fix(supervisor): Reorg corner cases handling
# Description

Handle following corner cases on Reorg

- Finalized block not available
- Reorg includes activation block rewinding

### PR DESCRIPTION
**Pull request by dhyaniarun1993**
Closes #2668

### CODE REVIEW

File: crates/supervisor/core/src/reorg/error.rs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+    /// Indicates an error occurred while interacting with the managed node.
+    #[error(transparent)]
+    ManagedNodeError(#[from] ManagedNodeError),
+
+    /// Indicates an error occurred while interacting with the database.
+    #[error(transparent)]
+    StorageError(#[from] StorageError),
+
+    /// Indicates and error which find rewind target for reorg.
```
Comment (emhane) [inline crates/supervisor/core/src/reorg/error.rs:21]:
```suggestion
    /// Indicates an error finding rewind target for reorg.
```

**Review by emhane — APPROVED** [review]
