### PR TITLE
patch(node/conductor): patch conductor bootstrap

### LINKED ISSUE #2571: fix(node/service): Support conductor bootstrap
## Overview

Currently, the `kona-node` supports operating within an `op-conductor` cluster. However, when bootstrapping a new cluster with [`op-conductor-ops`](https://github.com/ethereum-optimism/infra/tree/main/op-conductor-ops), `kona-node` fails to return an unsafe head pre-initialization.

We need to patch the `optimism_syncStatus` endpoint to return the current forkchoice of the EL prior to initialization, such that it never returns zero hashes prior to initialization.

### PR DESCRIPTION
**Pull request by theochap**
## Description

Close #2571

### CODE REVIEW

File: crates/node/engine/src/query.rs [hunk 1]
```diff
@@ -49,6 +50,9 @@ pub enum EngineQueries {
 /// An error that can occur when querying the engine.
 #[derive(Debug, thiserror::Error)]
 pub enum EngineQueriesError {
+    /// Failed to retrieve the L2 forkchoice state.
+    #[error("Failed to retrieve L2 forkchoice state: {0}")]
+    FailedToRetrieveL2ForkchoiceState(#[from] SyncStartError),
```
Comment (clabby) [inline crates/node/engine/src/query.rs:55]: This is unused now

**Review by clabby — APPROVED** [review]
