### PR TITLE
fix(supervisor): reorg at startup

### LINKED ISSUE #2683: fix(supervisor): reorg running at the startup

### PR DESCRIPTION
**Pull request by dhyaniarun1993**
Closes #2683

### CODE REVIEW

File: crates/supervisor/core/src/l1_watcher/watcher.rs [hunk 1]
```diff
@@ -148,43 +148,49 @@ where
     async fn handle_new_latest_block(
         &self,
         incoming_block: Block,
-        previous_block: &mut BlockNumHash,
+        previous_block: &mut Option<BlockNumHash>,
```
Comment (emhane) [inline crates/supervisor/core/src/l1_watcher/watcher.rs:151]: prefer if this method returns the new previous block (which could be the same as the argument) instead of passing a mutable reference - would that work here?

**Review by emhane — CHANGES_REQUESTED** [review]
